# Generated by Django 4.2.2 on 2023-10-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauka_api', '0002_tickerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
                ('message_type', models.CharField(max_length=15)),
                ('time_range', models.CharField(max_length=5)),
            ],
        ),
    ]
